cmake_minimum_required(VERSION 3.12)
set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)
set(CMAKE_CXX_STANDARD 20)
project(cube)
include_directories(include)
message($ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${PROJECT_SOURCE_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${PROJECT_SOURCE_DIR})
add_definitions(-DAPP_NAME=\"${PROJECT_NAME}\")
add_definitions(-DAPP_VERSION=\"0.1.0\")
aux_source_directory(${PROJECT_SOURCE_DIR}/src/runtime SRC_RUNTIME)
aux_source_directory(${PROJECT_SOURCE_DIR}/src/core SRC_CORE)
aux_source_directory(${PROJECT_SOURCE_DIR}/src/video SRC_VIDEO)
add_executable(${PROJECT_NAME} ${SRC_RUNTIME} ${SRC_CORE} ${SRC_VIDEO})
find_package(cJSON CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE cjson)
add_subdirectory(3rdparty/neo.js)
include_directories(3rdparty/neo.js/include)
target_link_libraries(${PROJECT_NAME} PRIVATE neo)
find_package(SDL3 CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE SDL3::SDL3)