cmake_minimum_required(VERSION 3.12)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_TOOLCHAIN_FILE $ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake CACHE STRING "")
project(underground)
find_package(cJSON CONFIG REQUIRED)
find_package(qjs CONFIG REQUIRED)

option(ENABLE_GRAPHIC "Use Graphic Render" OFF)

if(ENABLE_GRAPHIC)
    find_package(SDL3 CONFIG REQUIRED)
    find_package(SDL3_ttf CONFIG REQUIRED)
    add_definitions(-DRENDER_MODE=1)
else()
    add_definitions(-DRENDER_MODE=0)
endif()

add_definitions(-D_CRT_SECURE_NO_WARNINGS)
add_definitions(-DAPP_VERSION="0.1.0")
add_definitions(-DAPP_NAME="${PROJECT_NAME}")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${PROJECT_SOURCE_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${PROJECT_SOURCE_DIR})
include_directories(${PROJECT_SOURCE_DIR}/include)
aux_source_directory(${PROJECT_SOURCE_DIR}/src/core SOURCE_CORE)
aux_source_directory(${PROJECT_SOURCE_DIR}/src/runtime SOURCE_RUNTIME)
add_executable(${PROJECT_NAME} ${SOURCE_CORE} ${SOURCE_RUNTIME})

if(ENABLE_GRAPHIC)
    target_link_libraries(${PROJECT_NAME} PRIVATE cjson qjs SDL3::SDL3 SDL3_ttf::SDL3_ttf)
else()
    target_link_libraries(${PROJECT_NAME} PRIVATE cjson qjs stdc++exp)
endif()