[section .metadata]
.filename: D:\project\cube\script\add.mjs
.dirname: D:\project\cube\script
[section .constants]
.0: "add"
.1: "a"
.2: "b"
.3: "arguments"
.4: "(a, b) => a + b"
[section .data]
0: NEO_ASM_PUSH_SCOPE
2: NEO_ASM_PUSH_UNINITIALIZED
4: NEO_ASM_SET_CONST
6: NEO_ASM_DEF "add"
16: NEO_ASM_POP
18: NEO_ASM_JMP 136
28: NEO_ASM_PUSH_SCOPE
30: NEO_ASM_PUSH_UNDEFINED
32: NEO_ASM_DEF "a"
42: NEO_ASM_POP
44: NEO_ASM_PUSH_UNDEFINED
46: NEO_ASM_DEF "b"
56: NEO_ASM_POP
58: NEO_ASM_LOAD "arguments"
68: NEO_ASM_ITERATOR
70: NEO_ASM_NEXT
72: NEO_ASM_RESOLVE_NEXT
74: NEO_ASM_POP
76: NEO_ASM_STORE "a"
86: NEO_ASM_POP
88: NEO_ASM_NEXT
90: NEO_ASM_RESOLVE_NEXT
92: NEO_ASM_POP
94: NEO_ASM_STORE "b"
104: NEO_ASM_POP
106: NEO_ASM_POP
108: NEO_ASM_POP
110: NEO_ASM_LOAD "a"
120: NEO_ASM_LOAD "b"
130: NEO_ASM_ADD
132: NEO_ASM_RET
134: NEO_ASM_POP_SCOPE
136: NEO_ASM_PUSH_LAMBDA
138: NEO_ASM_SET_ADDRESS 28
148: NEO_ASM_SET_SOURCE "(a, b) => a + b"
158: NEO_ASM_STORE "add"
168: NEO_ASM_POP
170: NEO_ASM_LOAD "add"
180: NEO_ASM_EXPORT "add"
190: NEO_ASM_HLT
192: NEO_ASM_POP_SCOPE
